branch-defaults:
  default:
    environment: cancer-dev
global:
  application_name: cancer-dev
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2015.03 v2.0.0 running Python 2.7
  default_region: ap-northeast-1
  profile: eb-cli
  sc: null
